
inherit_from:
  - ./config/rubocop-suse.yml

# TODO: (mssola) Some methods are offending this cop. In the SUSE's style guide
# the approach is to use Rubocop's default value. In the near future I will
# fix this.
Metrics/MethodLength:
  Max: 252

# Not worth it, since numbers like ports are too weird in this format.
# NOTE: this is being discussed in the SUSE's coding style repo:
# https://github.com/SUSE/style-guides/pull/11
Style/NumericLiterals:
  Enabled: false

# It's convenient to mix both. This is something that SUSE's style guide does
# not specify, so we take the approach that we were following already.
Style/ClassAndModuleChildren:
  Enabled: false

# NOTE: (mssola) This would be nice, but there are too many errors on this for
# now and it's not urgent. I will fix this in the near future.
Style/Documentation:
  Enabled: false

AllCops:
  RunRailsCops: true

  Exclude:
    # Files that are out of our control and that are not excluded in the
    # default config of rubocop.
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - vendor/**/*
    - tmp/**/*
    - config/cronotab.rb
    - config/initializers/*
    - config/environments/*
