
# It's actually better for the eyes to add a new line around the block body if
# it's a big chunk of code (e.g. in tests).
Style/EmptyLinesAroundBlockBody:
  Enabled: false

# NOTE: the default for this is 80 columns long. This is a bit inconvenient for
# us, since we have *lots* of lines that would fail on this. Instead of fixing
# this now, we'll fix it in the future.
Metrics/LineLength:
  Max: 180
  # To make it possible to copy or click on URIs in the code, we allow lines
  # contaning a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https

# NOTE: as in the one before, this would be nice but there are too many errors
# on this and it's not urgent.
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 252

# This metric is *really* small by default. This value makes more sense.
Metrics/AbcSize:
  Max: 226

# Our use of "raise vs fail" is inconsitent. This is something that could be
# improved in the future, but it's not too much of a trouble right now.
Style/SignalException:
  Enabled: false

# Not worth it, since numbers like ports are too weird in this format.
Style/NumericLiterals:
  Enabled: false

# TODO: this is just for the Repository.handle_push_event.
Metrics/CyclomaticComplexity:
  Enabled: false

# TODO: this is just for the Repository.handle_push_event.
Metrics/PerceivedComplexity:
  Enabled: false

# We use a compact style instead of the default nested.
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# It complains on code that is just fine.
Style/MultilineOperationIndentation:
  Enabled: false

# It complains on code that is just fine.
Style/FirstParameterIndentation:
  Enabled: false

# It complains on code that is just fine.
Style/AlignParameters:
  Enabled: false

# NOTE: This would be nice, but there are too many errors on this for now and
# it's not urgent.
Style/Documentation:
  Enabled: false

AllCops:
  RunRailsCops: true

  Exclude:
    # Files that are out of our control and that are not excluded in the
    # default config of rubocop.
    - db/schema.rb
    - db/migrate/*
    - bin/*

