language: ruby
rvm:
  - 2.1.3
before_install:
  - |
    bash -c " # Install MariaDB
    sudo bash .travis_mariadb.sh
    "
before_script:
    - mysql -e 'create database portus_test;'
script:
  - 'bundle exec rspec spec'
  - 'bundle exec rubocop'
