version: 0.1
loglevel: debug
storage:
  filesystem:
    rootdirectory: /var/lib/docker-registry
http:
  addr: 0.0.0.0:80
auth:
  token:
    realm: http://portus.test.lan/v2/token
    service: registry.test.lan
    issuer: portus.test.lan
    rootcertbundle: /vagrant/vagrant/conf/ca_bundle/server.crt
notifications:
  endpoints:
    - name: portus
      url: http://portus.test.lan/event
      timeout: 500ms
      threshold: 5
      backoff: 1s
